# Generated by Django 4.2.4 on 2023-10-30 09:06

from django.db import migrations


def create_unique_brands(apps, schema_editor):
    shoe = apps.get_model('main_app', 'Shoe')
    unique_brands = apps.get_model('main_app', 'UniqueBrands')

    # shoe.objects.value_list('brand') -> takes all values in column 'brand'
    # shoe.objects.value_list('brand', flat=True) -> all values in one dimensional array
    # shoe.objects.values_list('brand', flat=True).distinct() -> all unique values
    unique_brand_names = shoe.objects.values_list('brand', flat=True).distinct()

    # make list of instances of unique_brands
    unique_brands_to_create = [unique_brands(brand_name=brand_name) for brand_name in unique_brand_names]

    # creat all instances into the model(table) at once
    unique_brands.objects.bulk_create(unique_brands_to_create)

    # not best practice, because for each iteration we insert into DB
    # for brand_name in unique_brand_names:
    #     unique_brands.objects.using(db_alias).create(brand_name=brand_name)


def delete_unique_brands(apps, schema_editor):
    unique_brands = apps.get_model('main_app', 'UniqueBrands')

    # takes all objects from DB and delete them. Same as TRUNCATE
    unique_brands.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(create_unique_brands, reverse_code=delete_unique_brands)
    ]
