# Generated by Django 4.2.4 on 2023-10-30 14:21

from django.db import migrations


def set_age_group(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')
    persons = person_model.objects.all()

    for record in persons:
        if record.age <= 12:
            record.age_group = 'Child'
        elif record.age <= 17:
            record.age_group = 'Teen'
        else:
            record.age_group = "Adult"

    person_model.objects.bulk_update(persons, ['age_group'])


def set_age_group_default(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')
    persons = person_model.objects.all()

    # returns metadata for field "age_group" and more specifically the default value
    age_group_default = person_model._meta.get_field('age_group').default

    for record in persons:
        record.age_group = age_group_default

    person_model.objects.bulk_update(persons, ['age_group'])


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0012_person'),
    ]

    operations = [
        migrations.RunPython(set_age_group, reverse_code=set_age_group_default)
    ]
