# Generated by Django 4.2.4 on 2023-10-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_migrate_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age_group',
            field=models.CharField(default='No age group', max_length=20),
        ),
    ]
