# Generated by Django 4.2.4 on 2023-10-30 15:05

from django.db import migrations


def set_rarity(apps, schema_editor):
    item_model = apps.get_mode('main_app', 'Item')
    items = item_model.objects.all()

    for rec in items:
        if rec.price <= 10:
            rec.rarity = "Rare"
        elif rec.price <= 20:
            rec.rarity = "Very Rare"
        elif rec.price <= 30:
            rec.rarity = "Extremely Rare"
        else:
            rec.rarity = "Mega Rare"

        item_model.objects.bulk_update(items, ['rarity'])


def set_rarity_default(apps, schema_editor):
    item_model = apps.get_mode('main_app', 'Item')
    items = item_model.objects.all()

    # returns metadata for field "rarity" and more specifically the default value
    rarity_default = item_model._meta.get_field('rarity').default

    for rec in items:
        rec.rarity = rarity_default

    item_model.objects.bulk_update(items, ['age_group'])


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0015_item'),
    ]

    operations = [
    ]
