# Generated by Django 4.2.4 on 2023-10-30 15:20

from django.db import migrations


def generate_price(apps, schema_editor):
    MULTIPLIER = 120

    smartphone_model = apps.get_model('main_app', 'Smartphone')
    smartphones = smartphone_model.objects.all()

    for rec in smartphones:
        rec.price = len(rec.brand) * MULTIPLIER

    smartphone_model.objects.bulk_update(smartphones, ['price'])


def generate_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    smartphones = smartphone_model.objects.all()

    for rec in smartphones:
        if rec.price < 750:
            rec.category = 'Cheap'
        else:
            rec.category = 'Expensive'

    smartphone_model.objects.bulk_update(smartphones, ['category'])


def set_to_default(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    smartphones = smartphone_model.objects.all()

    default_price = smartphone_model._meta.get_field('price').default
    default_category = smartphone_model._meta.get_field('category').default

    for rec in smartphones:
        rec.price = default_price
        rec.category = default_category

    smartphone_model.objects.bulk_update(smartphones, ['price', 'category'])


def generate_price_and_category(apps, schema_editor):
    generate_price(apps, schema_editor)
    generate_category(apps, schema_editor)


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0017_smartphone'),
    ]

    operations = [
        migrations.RunPython(generate_price_and_category, reverse_code=set_to_default)
    ]
