"""Add new field in Song model where to store music file as binary

Revision ID: 9224883ad9f5
Revises: 88c96903fde2
Create Date: 2023-11-29 16:23:34.037670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9224883ad9f5'
down_revision: Union[str, None] = '88c96903fde2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('misic_file_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'misic_file_data')
    # ### end Alembic commands ###
