"""Add new field in Song model where to store music file as binary

Revision ID: efa0fea4b0fd
Revises: 9224883ad9f5
Create Date: 2023-11-29 16:26:06.442339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efa0fea4b0fd'
down_revision: Union[str, None] = '9224883ad9f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('song_file_data', sa.LargeBinary(), nullable=True))
    op.drop_column('songs', 'misic_file_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('misic_file_data', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('songs', 'song_file_data')
    # ### end Alembic commands ###
