# Generated by Django 4.2.4 on 2023-10-24 06:20
import random
from django.db import migrations


def add_barcode(apps, schema_editor):
    # loads table
    Product = apps.get_model("main_app", "Product")

    # takes all entries from table
    all_products = Product.objects.all()

    # generated random number for each product
    all_barcodes = random.sample(range(100000000, 1000000000), len(all_products))

    for idx in range(len(all_products)):
        product = all_products[idx]
        product.barcode = all_barcodes[idx]
        product.save()


def reverse_add_barcode(apps, schema_editor):
    Product = apps.get_model("main_app", "Product")
    for product in Product.objects.all():
        product.barcode = 0
        product.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0003_product_barcode'),
    ]

    operations = [
        migrations.RunPython(add_barcode, reverse_code=reverse_add_barcode)
    ]
